version: "3.9"
networks: 
  rede1:
    driver:   
      bridge
services: 
  db:
    container_name: db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: potential_crud
      POSTGRES_PASSWORD: "12345"
    ports: 
      - "5432:5432"
    networks: 
      - rede1
  api:
    container_name: api
    links: 
      - db
    depends_on:
      - db
    build:
      context: ./api/
      dockerfile: Dockerfile
    restart: always
    ports: 
      - "4000:4000"
    networks: 
      - rede1
    tty: true
  front:
    container_name: front
    build: 
      "./front"
      
    restart: always
    ports: 
      - "8080:8080"
    links: 
      - db
      - api